---
title: "Lab 08 - University of Edinburgh Art Collection"
author: "Lindsay Stall"
date: "3/16/2023"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(skimr)
library(robotstxt)
```

```{r}
library(usethis)
use_git_config(user.name = "Lindsay Stall", 
               user.email = "stallm21@wfu.edu")
```

```{r}
paths_allowed("https://collections.ed.ac.uk/art)")
```

```{r}
uoe.art <- read_csv("data/uoe-art.csv")
```


### Exercise 9

```{r separate-title-date, error = TRUE}
uoe.art <- uoe.art %>%
  separate(title, into = c("title", "date"), sep = "\\(") %>%
  mutate(year = str_remove(date, "\\)") %>% as.numeric()) %>%
  select(title, artist, year, link)
```

### Exercise 10

```{r}
skim(uoe.art)
```
114 have artist missing; 1368 has year missing

```{r}
ggplot(data = uoe.art, aes(x = year)) + geom_histogram(binwidth = 100)
```


```{r}
uoe.art <- uoe.art %>%
  mutate(
    year2 = if_else(year == 2, 1964, year)
  )
```


```{r}
ggplot(data = uoe.art, aes(x = year2)) + geom_histogram(binwidth = 10)

```


```{r}
uoe.artist <- uoe.art %>%
  filter(artist == "Emma Gillies")
ggplot(data = uoe.artist, aes(x = artist)) + geom_bar()
```
Unknown and Emma Gillies had the most pieces of art.


```{r}
uoe.art %>% 
  filter(
    str_detect(title , "child") |
      str_detect(title , "Child")
  )
```
there were 10 pieces of art with the word child in it
